version: "3"
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  app:
    container_name: app
    image: fdf515/sheerdevelopment:0.1.0
    command: bundle exec puma -C config/puma.rb -p 3000
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/sheerdevelopment_production"
      RAILS_ENV: production
      HTTP_PORT: 3000
      VIRTUAL_HOST: sheerdevelopment.com
      LETSENCRYPT_HOST: sheerdevelopment.com
      LETSENCRYPT_EMAIL: "jiazhenxie515@gmail.com"
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db

  web-redirect:
    image: adamkdean/redirect
    environment:
      VIRTUAL_HOST: sheerdevelopment.com
      LETSENCRYPT_HOST: sheerdevelopment.com
      LETSENCRYPT_EMAIL: "jiazhenxie515@gmail.com"
      REDIRECT_LOCATION: "https://www.sheerdevelopment.com"
    networks:
      - app-network

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

volumes:
  pgdata:
  nginx-certs:
  nginx-vhost:
  nginx-html:

networks:
  app-network:
    driver: bridge
